# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0006_cocktail_recipe'),
        ('profiles', '0002_remove_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked_cocktails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.NullBooleanField()),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.Cocktail')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='templates/profile_images/<function upload_location at 0x103bc4048>'),
        ),
        migrations.AddField(
            model_name='liked_cocktails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
