# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160413_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liked_cocktails',
            new_name='Liked_cocktail',
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='templates/profile_images/<function upload_location at 0x103d29048>'),
        ),
    ]
