# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20160416_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_images/<function upload_location at 0x1033c4048>'),
        ),
    ]
