# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='drinks.Ingredient'),
            preserve_default=False,
        ),
    ]
