# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20160410_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cocktail',
            field=models.ManyToManyField(to='drinks.Cocktail'),
        ),
    ]
