# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_auto_20160410_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='recipe',
            field=models.TextField(default='No Recipe'),
        ),
    ]
