# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0006_cocktail_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='templates/cocktail_images'),
        ),
    ]
