# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0007_cocktail_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/cocktail_images'),
        ),
    ]
